### ISSUE TITLE
Inconsistent initialization/use of configuration for xsappname

### ISSUE THREAD

**Issue by okutyrin** [SAP/cloud-pysec#64]
If the `xsappname` is defined in the environment (and not in the config) then getting an error in "sap/xssec/security_context_xsuaa.py", line 375 (KeyError: 'xsappname')

The reason is that during the [initialization](https://github.com/SAP/cloud-pysec/blob/d90c9e0733fa9af68bd8ea0b1cf023cf482163ef/sap/xssec/security_context_xsuaa.py#L107), the `xsappname` value is copied from the environment to `_properties`, but not to `_config`, while the audience validation is trying to read it from `_config`. So, the initial validation of the config passes through, while the use at runtime fails.

**Comment by robertofalk** [comment]
Hi @okutyrin,
can you send me an example how you call the `xssec.create_security_context`?

I understand the bug you reported, but the thing is, supporting `XSAPPNAME` as an environment variable is legacy, as pointed out in the code [here](https://github.com/SAP/cloud-pysec/blob/d90c9e0733fa9af68bd8ea0b1cf023cf482163ef/sap/xssec/security_context_xsuaa.py#L104), and I have to admit, I don't quite get the scenario that was meant to be supported with this functionality since `config` is already a dict, so the application has to build this dict somehow (either extracting from VCAP_SERVICES or build it manually) so why supporting a 3rd way of providing the same information, I don't get it.
Roberto

**Comment by robertofalk** [comment]
closing it since there was no reply.
